stages:
  - lint
  - tests

image: psav/runner:latest
variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - dnf install python-pip git -y
  - pip install -U pip tox setuptools setuptools-scm pre-commit

py36:
  stage: tests
  script:
    - tox -epy36
  tags:
    - shared

linting:
  stage: lint
  script:
    - pre-commit run --all
  tags:
    - shared
